version: "3.6"
services:

  # ###
  # Core Services offered in this repo
  # ###

  zeo:
    build:
      context: .
      target: zeo
    ports:
      - "8100"
    command: bash -c "bin/zeoserver show all && bin/zeoserver fg"
    volumes:
      - zodb-data:/app/var/filestorage/:rw
      - .dockerfiles/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh

  web:
    build:
      context: .
      target: web
    ports:
      - "8080"
    command: bash -c "bin/client show all && bin/client fg"
    environment:
      - LEGACY_ZEO_HOST=zeo
    volumes:
      - .dockerfiles/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - shared-files1:/var/www/files
      - shared-files2:/var/www/files2
      - shared-files3:/var/www/files3
      - shared-files4:/var/www/files4

  pdf-gen:
    build:
      context: .
      target: pdf-gen
    ports:
      - "8080"
    command: bash -c "bin/pdf_gen show all && bin/pdf_gen fg"
    environment:
      - LEGACY_ZEO_HOST=zeo
    volumes:
      - .dockerfiles/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - shared-files1:/var/www/files
      - shared-files2:/var/www/files2
      - shared-files3:/var/www/files3
      - shared-files4:/var/www/files4

  # ###
  # Dependency Services
  # ###

  # unoconv:
  #   ???

  # exim:
  #   ???

  memcached:
    image: memcached:1.5

  db:
    image: openstax/cnx-db:latest
    ports:
      # Exposes the port to a random external port number.
      # Use `docker ps` to find the external port mapping.
      - "5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    # If you'd like to load the database with data, have a look at:
    # https://github.com/Connexions/devops/wiki/How-To%3A-Get-a-Slim-Database-Dump
    # But do keep in mind that it will be wiped away if you are
    # also running the unit tests

volumes:
  pg-data:
  zodb-data:
  shared-files1:
  shared-files2:
  shared-files3:
  shared-files4:
